# Conclusion {background-color="#A1D6F4"}

- Property & Casualty (P&C) Industry Overview
- U.S. Insurance Regulation
- Geospatial Data in Homeowners
  - Territories
  - Features
  - Combining Territories & Features
- Modeling the Cost of Home Insurance
- Example Territory Maps
- Location-specific Data
- Conclusion
- Happy Hour

# Learn More! {background-color="#A1D6F4"}

## High-level Resources {background-color="#A1D6F4"}

-   [Insurance Information Institute](https://www.iii.org/)
-   [The Institutes](https://web.theinstitutes.org/)
-   [Casualty Actuarial Society](https://www.casact.org/)
-   [Society of Actuaries](https://www.soa.org/)
-   [SERFF: System for Electronic Rates & Forms Filings](https://www.serff.com/)
-   [Be An Actuary](https://www.beanactuary.org/)
-   [National Association of Insurance Commissioners](https://content.naic.org/)
-   [Wikipedia: State-Based Insurance Regulation](https://en.wikipedia.org/wiki/Insurance_regulatory_law#State-based_insurance_regulation)

## Semi-technical Resources {background-color="#A1D6F4"}

-   [An Actuarial Review of Homeowners By Peril Rating](https://ar.casact.org/an-actuarial-review-of-homeowners-by-peril-rating/)
-   [Finger - Risk Classification](https://www.casact.org/abstract/risk-classification-chapter-6)

## Technical Resources {background-color="#A1D6F4"}

-   [Distributions for Actuaries](https://www.casact.org/sites/default/files/2021-02/02-Bahnemann.pdf)
-   [Generalized Linear Models for Insurance Rating](https://www.casact.org/sites/default/files/2021-01/05-Goldburd-Khare-Tevet.pdf)
-   [An Actuarial Review of Homeowners By Peril Rating](https://ar.casact.org/an-actuarial-review-of-homeowners-by-peril-rating/)

## Data Sources (1/2) {background-color="#A1D6F4"}

### Census Bureau Shapefiles

- ftp2.census.gov username "anonymous" / no password
- State Shapefile: ftp://ftp2.census.gov/geo/tiger/TIGER2024/STATE/tl_2024_us_state.zip
- County Shapefile: ftp://ftp2.census.gov/geo/tiger/TIGER2024/COUNTY/tl_2024_us_county.zip
- ZIP Code Tabulation Areas: ftp://ftp2.census.gov/geo/tiger/TIGER2024/ZCTA520/tl_2024_us_zcta520.zip
- Census Tract: ftp://ftp2.census.gov/geo/tiger/TIGER2024/TRACT/tl_2024_36_tract.zip
- Census Block Group: ftp://ftp2.census.gov/geo/tiger/TIGER2024/BG/tl_2024_36_bg.zip
- Census Block: ftp://ftp2.census.gov/geo/tiger/TIGER2024/TABBLOCK20/tl_2024_36_tabblock20.zip

## Data Sources (2/2) {background-color="#A1D6F4"}

### Military Grid Reference System (MGRS) Shapefile

- 1km grid: https://earth-info.nga.mil/index.php?dir=coordsys&action=mgrs-1km-polyline-dloads

### SSURGO Web Soil Survey Shapefile

- Download **by county**: https://websoilsurvey.nrcs.usda.gov/app/WebSoilSurvey.aspx
- New York county: https://websoilsurvey.sc.egov.usda.gov/DSD/Download/Cache/SSA/wss_SSA_NY061_soildb_US_2003_[2024-08-29].zip

###  National Land Cover Database Raster

- Website: https://www.mrlc.gov/data
- 2023 NLCD Raster: https://www.mrlc.gov/downloads/sciweb1/shared/mrlc/data-bundles/Annual_NLCD_LndCov_2023_CU_C1V1.zip