# Example Territory Maps

Travelers Quantum Home 2.0 Vermont?
Nevada esurance 0.05, 0.1, 0.2, 0.4 grid  SERFF ESUR-129867328 Page 920

## State Farm (#1 in New York)

State Farm Group (176) State Farm Fire And Casualty Company (25143)

Location Rating

Hurrican vs. Non-Hurricane

## Allstate (#2 & 5 in New York)

Allstate Insurance Group (8) Allstate Vehicle and Property Insurance Company (37907) - Several variables interact with zone. Not trying to parse that

Allstate Insurance Group (8) Allstate Insurance Company (19232) - Territories are on scanned in sheets of paper

## Chubb

Chubb Ltd Grp (626) Chubb National Insurance Company (10052)

Hurricane Wind
Non-Hurricane Wind
All Other Perils

Governors Island 97
Fort Charles 05
Rest of County 18

A few factor sections - figure out which one?
Condo / Coop Factors Page 34
Renters Page 36

Factors Start at Page 81, 

## Liberty Mutual

Liberty Mutual Group (111) Liberty Insurance Corporation (42404)

Ranked 4th

NYP66556.pdf
Page 102
Rates - Page 107
H4/H6 - Page 109

## NYCM

Nycm Insurance Group (2518) New York Central Mutual Fire Insurance Company (14834)
Ranked 6th
NYP66579

By county
A few split counties. E.g. Buffalo part of Erie county
Nassau and Suffolk by ZIP
New York County is territory 05. 1.270 factor for HO04/HO06


## Travelers Insurance
Ranked 9th

66405

ZIP Code

## Insurance Services Office (Vendor)

## Explore Information Services ()

## Core Logic

